### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by hiroshiyukawa111**
## Checklist before sharing the notebook to the community
- [x] Notebook is in the format `Name_Score_Fall22_Lab4.ipynb`
- [x] Check for import statements

### CODE REVIEW

**Review by mrvee-qC-bee — CHANGES_REQUESTED** [review]
Hello! Can you please add your notebook in the solutions-by-participants folder? :D Thank you so much! :D Fyi @q-inho

**Comment by hiroshiyukawa111** [comment]
Hi, I just added my notebooks to the solutions-by-participants folder. And I deleted my notebooks in the main area.

**Comment by mrvee-qC-bee** [comment]
Thank you so much @hiroshiyukawa111 ! This looks ok now! Merging your solution! 😁

**Review by mrvee-qC-bee — APPROVED** [review]
Approved! FYI @q-inho

**Pull request merged**
